# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  config.vm.define "node01" do |node01|
    node01.vm.box = "centos/7"
    node01.vm.network "private_network", ip: "192.168.51.100"
  end

  config.vm.define "node02" do |node02|
    node02.vm.box = "centos/7"
    node02.vm.network "private_network", ip: "192.168.51.110"
  end

  config.vm.define "node03" do |node03|
    node03.vm.box = "centos/7"
    node03.vm.network "private_network", ip: "192.168.51.120"
  end
end

